### PR TITLE
Run debug policy tests in CI

### PR DESCRIPTION
**Pull request by JohnPMerrill**

### CODE REVIEW

**Comment by amstrnad** [comment]
I'm curious how much longer this will make the test run take. If it's significant, we might want to do a reduced test set.

**Comment by JohnPMerrill** [comment]
@amstrnad agreed. we can judge based on the first CI run

**Comment by amstrnad** [comment]
It seems to only slow down the CI run by 15-20 minutes, which is better than expected. However, the `malloc_prof_2` tests currently time out, and the debug test results are overwriting the non-debug results (they create the same `.xml` filename with test results).

**Comment by natestuder** [comment]
Is there a way to make the debug tests run only if the normal run fails?

**Comment by JohnPMerrill** [comment]
@natestuder I don't think we'd want to do that. The point of having the debug tests run is to make sure we didn't break them

**Comment by amstrnad** [comment]
I think for now, we should restrict what tests/policies are run with debug. Eventually we should run them all (or even better, figure out how to rerun any failed tests), but for now, I think less is more.

If we add `TESTS=hello_works_1,cfi/jump_data_fails_1 POLICIES=cfi,heap`, we'll still know if anything major breaks, and it won't take an extra hour.

**Comment by JohnPMerrill** [comment]
@amstrnad agreed. Over a few trials, increasing the timeout on the debug tests hasn't reliably allowed them to all pass. Better to test just one positive and negative test as a sanity check, as you suggest

**Comment by ccasin** [comment]
Also agree that running a few specific tests for now is a good idea.  In general the amount of debug output that can be generated by the heap policy on long-running tests may mean it's never possible to run them all in CI.

**Pull request merged**
